@echo off
echo Activating virtual environment...
call venv\Scripts\activate

echo Preprocessing markdown files...
python preprocess_markdown.py

echo Indexing documents...
python index_documents.py

echo Starting Flask app...
python app.py
